//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinanceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCOMETAX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INCOMETAX()
        {
            this.INCOMETAXBRACKETs = new HashSet<INCOMETAXBRACKET>();
        }
    
        public decimal ID { get; set; }
        public string WHO { get; set; }
        public string STATE { get; set; }
        public string FILINGTYPE { get; set; }
        public System.DateTime YEAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INCOMETAXBRACKET> INCOMETAXBRACKETs { get; set; }
    }
}
