//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinanceWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PFContext : DbContext
    {
        public PFContext()
            : base("name=PFContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INCOMETAX> INCOMETAXes { get; set; }
        public virtual DbSet<INCOMETAXBRACKET> INCOMETAXBRACKETs { get; set; }
        public virtual DbSet<LOAN> LOANs { get; set; }
        public virtual DbSet<PERSON> People { get; set; }
        public virtual DbSet<SAVING> SAVINGS { get; set; }
        public virtual DbSet<TAX> TAXes { get; set; }
        public virtual DbSet<WAGE> WAGEs { get; set; }
    }
}
